### ISSUE TITLE
Review `compute_spl()` unit tests

### ISSUE THREAD

**Issue by tonyfujs** [PIP-Technical-Team/wbpip#218]
Hi @randrescastaneda 
I added some basic unit tests for the `compute_spl()` function. Can you please take a look when you get a chance to make sure they are relevant ones? Thanks!

**Comment by randrescastaneda** [comment]
#860pxwg4w

**Comment by randrescastaneda** [comment]
Hi @tonyfujs , 

I review the tests you made [here](https://github.com/PIP-Technical-Team/wbpip/pull/216/files#diff-44ffa32d80b6a6f31136cc601cdf25094e76e16e6f6d7fd48d58980336eee60e) and they are fine. 

Thanks.
